### ISSUE TITLE
find site definition from url, and find sitemap from site definition

### ISSUE THREAD

**Issue by larswoetmann** [Geta/SEO.Sitemaps#109]
in multisite we can have 2 sites with the following domains: abc.xyz.com and xyz.com

if the sitemap for abc.xyz.com is defined before the sitemap for xyz.com then when we try to get the sitemap for xyz.com then we get the one for abc.xyz.com because GetSitemapData(string requestUrl) uses Contains to find the sitemap.

if episerver SiteDefinition is used instead then this problem can be fixed. 
At the same time this also fixes the problem where 1 site have more than one host definition like both abc.com and xyz.com where abc.com is the primary. then the sitemap can only be accessed from abc.com/sitemap.xml not xyz.com/sitemap.xml

i did not have access to push a new branch (maybe i dont know how to set it up correctly). So here is the code that should fix the problem:

```
        private readonly ISiteDefinitionResolver _siteDefinitionResolver;

        public SitemapRepository(ILanguageBranchRepository languageBranchRepository, ISiteDefinitionResolver siteDefinitionResolver)
        {
            if (languageBranchRepository == null) throw new ArgumentNullException("languageBranchRepository");
            _languageBranchRepository = languageBranchRepository;
            _siteDefinitionResolver = siteDefinitionResolver;
        }

        public SitemapData GetSitemapData(string requestUrl)
        {
            var url = new Url(requestUrl); 
            
            var host = url.Path.TrimStart('/').ToLowerInvariant();

            var siteDefinition = _siteDefinitionResolver.GetByHostname(url.Host, true, out _);
            if (siteDefinition == null)
            {
                return null;
            }

            return GetAllSitemapData().FirstOrDefault(x => GetHostWithLanguage(x) == host && (x.SiteUrl == null || siteDefinition.Hosts.Any(h => h.Name == new Url(x.SiteUrl).Host)));
        }
```

**Comment by patkleef** [comment]
Fixed in version 3.1.3, will be available on Episerver NuGet feed once they approve it.
