### ISSUE TITLE
Bug: generating in debug mode fails if page name contains double dash "--"

### ISSUE THREAD

**Issue by lanorkin** [Geta/SEO.Sitemaps#111]
If debug mode set for sitemap, then this line tries to include page name into XML comment:

https://github.com/Geta/SEO.Sitemaps/blob/aeffd5bbfb289c82c0bb9bd3575b65fd04ccb877/src/Geta.SEO.Sitemaps/XML/SitemapXmlGenerator.cs#L356

That fails if page name contains "--" in it:
```
System.ArgumentException: An XML comment cannot contain '--', and '-' cannot be the last character.
```

And as a result job fails with not really helpful message:

> Error creating sitemap for "sitemap.xml"

**Comment by patkleef** [comment]
@lanorkin fixed in version 3.1.1 : https://github.com/Geta/SEO.Sitemaps/blob/master/CHANGELOG.md#311
