### ISSUE TITLE
Editor for PropertySEOSitemaps breaks Edit UI for IE11 and lower

### ISSUE THREAD

**Issue by lanorkin** [Geta/SEO.Sitemaps#118]
Steps to reproduce:

1. Follow guide https://github.com/Geta/SEO.Sitemaps#adding-sitemap-properties-to-all-content-pages to add property for page
2. Open page for edit in IE11

Expected: 
Everything's OK

Actual:
EpiServer edit UI is broken, cannot edit page properties, error in console:

![image](https://user-images.githubusercontent.com/3510383/70508563-bdd58c80-1b3f-11ea-9038-316c4e6fbe4d.png)

**Comment by patkleef** [comment]
Thanks @lanorkin for reporting and solving this issue. Version 3.1.2 is uploaded and will be released by Episerver once they approve.
