### ISSUE TITLE
Add option to modify filtering based on PageShortcutType

### ISSUE THREAD

**Issue by tuomasinkinen** [Geta/SEO.Sitemaps#121]
We have a need to remove pages from sitemap that have their content fetched from another page, ie. PageShortcutType.FetchData.

Would it be possible to configure this somehow already, or could this feature be added?

**Comment by lanorkin** [comment]
One of options I see - you can implement sitemap property like described here https://github.com/Geta/SEO.Sitemaps#adding-sitemap-properties-to-all-content-pages and manually uncheck "Enabled" for pages you want to skip in sitemap

**Comment by tuomasinkinen** [comment]
Yes, this is how we have been doing it. It's just becoming tedious to do this for all required pages, and then it's not not easy to see which pages have it set and which not. And all of the pages have in common that they are fetched from other pages, so it would be so easy to just filter based on that.
But thanks for the quick reply!

**Comment by patkleef** [comment]
@tuomasinkinen I think this is a very specific use case. I do agree there should be an easy way for filtering out pages. Like @lanorkin is saying you could use the property. Another solution could be where we allow developers to create an (or multiple) implementations of the `IContentFilter` and use that in the package to see if the content item should be included in the sitemap or not.

**Comment by tuube** [comment]
Yes, it would be wonderful if we could make our own implementation of the IContentFilter, and inject it from the EPI-project.

**Comment by patkleef** [comment]
I went through the code to see how this can be implemented, but I think there is a simple solution for this. The IContentFilter is already available because it's a public interface so you can make your own custom implementation (make sure to call the base class!).

```
public class SiteContentFilter : ContentFilter
    {
        public override bool ShouldExcludeContent(IContent content)
        {
            if (base.ShouldExcludeContent(content))
            {
                return true;
            }

            // Custom logic here

            return false;
        }
    }
```

Register in your DI container.

`services.AddTransient<IContentFilter, SiteContentFilter>();`

I'll add this to the documentation.
