### ISSUE TITLE
SEO Sitemaps unable to serve sitemaps on languages with custom web address

### ISSUE THREAD

**Issue by danielhalse** [Geta/SEO.Sitemaps#122]
Replication Steps:

Change a language to use a custom web address.
For example uk for en-GB
Setup a /uk/sitemaps.xml sitemap
Run the scheduled job
While logged in to Episerver you can view this sitemap
Logout of CMS
Try to access sitemap
You will be redirected to /uk/ with a 302 redirect.

If you change the custom web address back to the default it will work on the default.

Seen in 2.0.8 and in latest version

**Comment by frederikvig** [comment]
We're not doing any redirects per se, we have only added routes for the different scenarios, see: https://github.com/Geta/SEO.Sitemaps/blob/master/src/Geta.SEO.Sitemaps/SitemapInitialization.cs#L29

Could there be something else in your code that kicks in and does the 302 redirect? You could try adding a specific route for it to the route table and see if that helps.

**Comment by danielhalse** [comment]
I disabled SEO Toolbox and cleared the rewrite file but was still getting the behaviour. We also have ADFS but that is not easily disabled.
Checking the class you highlighted it is using MapRoute which is not Episerver aware so will not be able to see the custom language routes in CMS. Will try a specific route to push to the controller.

**Comment by danielhalse** [comment]
I can make it work with a hard coded route to the controller.
Most routes we have use MapContentRoute to handle the custom language stems but there is no page to anchor it to in /uk/sitemap.xml so I get a null contentLink issue if I try to use that method.

**Comment by danielhalse** [comment]
Could not replicate in Alloy Tech.
So will look at other causes.
