### ISSUE TITLE
Simple Address Support

### ISSUE THREAD

**Issue by Ranger1230** [Geta/SEO.Sitemaps#125]
For our site, we utilize the Simple Address to make our URLs SEO friendly. It would be nice if there was an option to have this use the Simple Address for a page if it has one instead of the full url.

**Comment by patkleef** [comment]
Marked this as an enhancement. A possible solution is to make it possible to override logic in the package to get URL from IContent. See `SitemapXmlGenerator`.

**Comment by adnanzameer** [comment]
@Ranger1230 @patkleef  funny enough I once changed the codebase to support Simple Address for one of the projects and after refining the code I created a PR  https://github.com/Geta/SEO.Sitemaps/pull/134. 

might be useful to you

**Comment by patkleef** [comment]
@adnanzameer @Ranger1230 will be available in version 3.1.5. Will publish new version to Episerver, after they reviewed it will be ready on the NuGet feed.

**Comment by patkleef** [comment]
No, will be available in version 4.0.0 because new version will contain breaking changes.
