### ISSUE TITLE
404 for "sitemap.xml"

### ISSUE THREAD

**Issue by baier** [Geta/SEO.Sitemaps#130]
We get an error with http status code 404 whenever we navigate to <our-host>/sitemap.xml. The sitemap is generated successfully. We host our solution in Azure and use Azure Front Door. When we use the url for the azurewebsite directly, the sitemap is shown, but with the incorrect host url.

![image](https://user-images.githubusercontent.com/1081200/91699591-ca3dc180-eb74-11ea-8997-17fec42cbb41.png)
![image](https://user-images.githubusercontent.com/1081200/91699843-2f91b280-eb75-11ea-87d5-424a3cece9d9.png)

**Comment by JasonRodman** [comment]
Any news on this? I upgraded to 3.1.2 and it stopped working with this error.

**Comment by patkleef** [comment]
Could you share how you configured your site URLs in the admin mode and your sitemap URL? Could you take a look at these unit tests to see if your scenario is covered? => https://github.com/Geta/SEO.Sitemaps/blob/master/test/Geta.SEO.Sitemaps.Tests/SitemapRepositoryTests.cs#L107

**Comment by JasonRodman** [comment]
Not really anything special with the configuration. This is how I have it configured for local development.
![image](https://user-images.githubusercontent.com/2798712/98735261-1aa17e80-2371-11eb-8fb5-3447566846cf.png)

**Comment by patkleef** [comment]
What about your site URLs under managed websites (admin mode)? How is that configured.

**Comment by JasonRodman** [comment]
![image](https://user-images.githubusercontent.com/2798712/98736075-5721aa00-2372-11eb-9b7a-d0184ac6a2b8.png)

**Comment by patkleef** [comment]
Thanks, I'll try to reproduce this.

**Comment by patkleef** [comment]
@JasonRodman I was able to reproduce the problem, thanks for reporting the bug.

I opened a pull request to solve this problem: https://github.com/Geta/SEO.Sitemaps/pull/133

Once it's reviewed and merged I'll submit the package to Episerver so they can publish a new version of the package.

**Comment by patkleef** [comment]
Version 3.1.4 is submitted to Episerver for review.
