### ISSUE TITLE
upgrading from 3.1.3 to 4.0.0

### ISSUE THREAD

**Issue by gatisb** [Geta/SEO.Sitemaps#145]
folder is not deleted:
`modules\Geta.SEO.Sitemaps`
leading to:
`modules\_protected\Geta.SEO.Sitemaps`
not served from zip file

**Comment by patkleef** [comment]
Like discussed can't reproduce tried with clean Alloy site and installed version 3. Upgraded to 4, old resources were removed and new ZIP file was added.
