### ISSUE TITLE
Sitemap.xml file not created in root of website

### ISSUE THREAD

**Issue by hn3etta** [Geta/SEO.Sitemaps#17]
Hi,

I am having issues getting the sitemap.xml file created in my root EPiServer 7.18 instance.  I have everything configured properly in the "Search engine sitemap settings" admin screen and when I run the job everything completes successfully with 388 entries.  When I peruse for the sitemap file it doesn't exist.  I searched the entire drive without any luck.

I have tried both the Nuget package and the Git source repo added to my solution.  No errors listed in the EPi logs either.  For giggles I added the following line in the SitemapXmlGenerator.cs file to see if I could get something to write out to the filesystem.

doc.Save(this.SitemapData.Host);

When I run this locally the file is created successfully in the c:\program files (x86)\IISExpress directory.  When this code is run from a development server the file tries to write to  c:\windows\system32\inetsrv\ directory (Access is denied).

Any help is greatly appreciated.

**Comment by frederikvig** [comment]
1. How does your ASP.NET routing configuration look?
2. What have you configured for your host?

Cheers

Frederik

**Comment by hn3etta** [comment]
Here is our routing config.  We use this route to pull news content from an OData end-point.

    [InitializableModule]
    public class RouteConfig : IInitializableModule
    {
        public void Initialize(InitializationEngine context)
        {
            RegisterRoutes(RouteTable.Routes);
        }

        private void RegisterRoutes(RouteCollection routes)
        {
            var newsPageId = ConfigurationManager.AppSettings[Global.AppSettingsKey.NewsArticleDetailContentReferenceId];
            var segment = new TitleSegment("title", new ContentReference(newsPageId));
            var routingParameters = new MapContentRouteParameters
                {
                    SegmentMappings = new Dictionary<string, ISegment>()
                };
            routingParameters.SegmentMappings.Add("title", segment);

            routes.MapContentRoute(
                name: "NewsArticleDetail",
                url: "{language}/about-imation/news/{title}/{action}",
                defaults: new { action = "index" },
                parameters: routingParameters);
        }

        public void Uninitialize(InitializationEngine context)
        {
        }

        public void Preload(string[] parameters)
        {
        }
    }

    public class TitleSegment : SegmentBase
    {
        private ContentReference _contentLink;

        public TitleSegment(string name, ContentReference contentLink)
            : base(name)
        {
            _contentLink = contentLink;
        }

        public override string GetVirtualPathSegment(RequestContext requestContext, RouteValueDictionary values)
        {
            return null;
        }

        public override bool RouteDataMatch(SegmentContext context)
        {
            var segmentPair = context.GetNextValue(context.RemainingPath);
            var title = segmentPair.Next;

            if (!string.IsNullOrEmpty(title) && IsValidTitle(title))
            {
                context.RemainingPath = segmentPair.Remaining;
                context.RoutedContentLink = _contentLink;
                context.RouteData.Values.Add("title", title);
                return true;
            }

            return false;
        }

        private bool IsValidTitle(string title)
        {
            return NewsHelper.NewsArticleExists(title);
        }
    }

Host setup
  -  IIS 8 site binding with no Host name and IP Address of * for port 8011
  -  EPi Manage Websites
     -  URL https://www.imation.com
        Host Names
          - oakwebepidev02.imation.com:8011    en
          - *
          - www.imation.com

Search engine sitemap settings
  Host: https://www.imation.com
  Path to include:
  Path to avoid:
  Root page ID: 9
  Debug info: 0
  Format: Standard

**Comment by garkavy** [comment]
Does it work with Root page ID -1?
Does Application pool has permission to write the file to the site's root? 
The latter looks like the cause of the issue.

**Comment by shreyasingh25** [comment]
Did you get this resolved? 
I have verified that application pool has permission to write the file to the site's root
