### ISSUE TITLE
Is there a way to extend the sitemap.xml list?

### ISSUE THREAD

**Issue by wiske80** [Geta/SEO.Sitemaps#18]
Why i ask: For our client we have a couple of integrations with systems and we have virtual pages. (from xml feed). So those pages are not in the CMS tree, but we would like to add(append) them to the current generated sitemap.xml... could we hook into this some way?

**Comment by frederikvig** [comment]
You can create a separate sitemap for the virtual pages (you can have multiple sitemaps) and link to all your sitemaps from robots.txt.

**Comment by wiske80** [comment]
ahh.. thats a good one... didn't think of that... thanks mate!
