### ISSUE TITLE
Cant access xml

### ISSUE THREAD

**Issue by cbublies** [Geta/SEO.Sitemaps#20]
Hi.
Im currently on Episerver 7.5 with a WebForms-project and i cant access the generated xml. 
I can view the xml through the viewbutton in admin-mode("Search engine sitemap settings") but when i try to access the xml through the host-url i get "No parameterless constructor defined for this object.".

What have i done wrong?
![untitled](https://cloud.githubusercontent.com/assets/9570875/9413255/158523dc-4831-11e5-85d7-ba07709123a9.png)

**Comment by frederikvig** [comment]
Hi
Which version of the sitemap module are you using?

Frederik

**Comment by cbublies** [comment]
Im using 1.4.1.

**Comment by cbublies** [comment]
It seems that the xml is generated på it dosent seem to be saved in my folder.

**Comment by MattisOlsson** [comment]
A new package has been uploaded to the EPiServer NuGet feed that fixes this issue. The problem was that an instance of the Sitemap controller could not be created in WebForms projects that doesn't have any dependency resolver set up for MVC.
