### ISSUE TITLE
What is the recommended way to disable pagetypes that shall not be indexed?

### ISSUE THREAD

**Issue by oyvindwh** [Geta/SEO.Sitemaps#21]
Some pagetypes, ex. Thank You pages, Container pages etc should not be indexed by Google and therefore not be a part of the sitemap.  Instead of changing value on each page, there should be a way of excluding pagetypes. How do you implement this in your projects?

/Øyvind

**Comment by frederikvig** [comment]
Right now this is only supported on a page level not page type. Container pages won't be added since they don't have a template. For thank you pages we usually use standard/article page where we then  exclude that specific page. If you wanted to automatically exclude specific content types you could always set the default value of the exclude property to true.

**Comment by oyvindwh** [comment]
I would rather always set the Enable to false for the specific pagetype, in this case the Thank You Page. The default will only hit the pages that are new.

Something like this;

        [Display(
        GroupName = SystemTabNames.Content,
        Order = 40)]
        [ScaffoldColumn(true)]
        [BackingType(typeof(PropertyString))]
        public virtual PropertySEOSitemaps SEOSitemaps
        {
            get
            {
                var settings = this.GetPropertyValue(p => p.SEOSitemaps);

                if (settings == null)
                {
                    settings = new PropertySEOSitemaps() { ChangeFreq = "weekly", Enabled = false, Priority = "0.5" };
                }
                else
                {
                    settings.Enabled = false;
                }

                return settings;

            }
            set { this.SetPropertyValue(p => p.SEOSitemaps, value); }
        }

Then the job should get Enabled=false in the ContentFilter.IsSitemapPropertyEnabled and the page should not be a part of the sitemap. But, the page still is a part of the sitemap.

**Comment by garkavy** [comment]
it is now possible to disable page types from inclusion to the site map (as per previous comment).

**Comment by saintjon** [comment]
How do we do this now when virtual PropertySEOSitemaps is changed to virtual string? https://github.com/Geta/SEO.Sitemaps/issues/27
