### ISSUE TITLE
Support for EPiServer 9

### ISSUE THREAD

**Issue by gitDeveloper1** [Geta/SEO.Sitemaps#22]
Since EPiServer.BaseLibrary.dll has been removed in EPiServer 9 and there is a reference to it in Geta.SEO.Sitemaps, the EPiServer site cant be loaded with Geta.SEO.Sitemaps.

**Comment by frederikvig** [comment]
Just uploaded new packages (1.5.x and newer) with support for EPiServer 9. Should be approved soon.
