### ISSUE TITLE
how to let the Sitemap generator generate HTTPS links instead of HTTP links

### ISSUE THREAD

**Issue by wiske80** [Geta/SEO.Sitemaps#25]
The client site is running on https, but the sitemap.xml generates all links in http. 

Am i missing something to let it force the links to be in https format?

**Comment by frederikvig** [comment]
How does your site configuration look? (manage websites)

**Comment by wiske80** [comment]
haha.. nevermind.. you comment made me look at it. and it seems the primary should be in https format, then the sitemap tool wil take all the urls as https.. 

fixed.. but i hope you can check the Geta.Tags issue.. that one is more important :)
