### ISSUE TITLE
No longer works with < EPiServer 9

### ISSUE THREAD

**Issue by dbengtsson** [Geta/SEO.Sitemaps#26]
The nuget package requires EPi > 9 to be installed so can't install the nuget package on epi 8.5

**Comment by frederikvig** [comment]
There should be an older version that supports Episerver < 9

**Comment by dbengtsson** [comment]
Ah yes, Didn't know you could specify old versions with nuget. 
1.4.* for Epi 8 and 1.3.* for Epi 7. Closing issue.
