### ISSUE TITLE
Adding SEOSitemap Properties to PageData

### ISSUE THREAD

**Issue by sayeedchoudhury** [Geta/SEO.Sitemaps#27]
Is it possible to add the SEOSItemap Properties to the PageData itself instead of using the Dynamic Properties?

**Comment by frederikvig** [comment]
Yup, that should be fine. Just use the same name.

**Comment by sayeedchoudhury** [comment]
I tried using it. I keep getting error.

`public virtual PropertySEOSitemaps SEOSitemaps { get; set; }`

**Comment by frederikvig** [comment]
Try adding the backing type attribute as well: 
```
[BackingType(typeof(PropertyString))]
public virtual PropertySEOSitemaps SEOSitemaps { get; set; }
```

**Comment by sayeedchoudhury** [comment]
Throws error:
`The property 'SEOSitemaps' on content type 'SitePageData' is of type 'Geta.SEO.Sitemaps.SpecializedProperties.PropertySEOSitemaps' that cannot be backed by PropertyString, it only only supports types String`

I tried using:
`[BackingType(typeof(PropertySEOSitemaps))]
        public virtual string SEOSitemaps { get; set; }`

It works, but i just get a text field on the edit mode. How do I get the proper controls for the property?

**Comment by frederikvig** [comment]
Ah yes sorry. The property should be updated to use the new property system in Episerver. Anyway, this should get it to show up in edit mode:
```
[UIHint(UIHint.Legacy, PresentationLayer.Edit)]
[BackingType(typeof(PropertySEOSitemaps))]
public virtual string SEOSitemaps { get; set; }
```

**Comment by sayeedchoudhury** [comment]
Just managed to get it working as below:
'[BackingType(typeof(PropertySEOSitemaps))]
 [UIHint(EPiServer.Web.UIHint.Legacy)] 
 public virtual string SEOSitemaps { get; set; }'

**Comment by sayeedchoudhury** [comment]
Thanks for your help.
