### ISSUE TITLE
PropertySEOSitemaps for commerce sitemap

### ISSUE THREAD

**Issue by tiasmc** [Geta/SEO.Sitemaps#29]
Is it possible to add the PropertySEOSitemaps to commerce products?
I need to set the priority for all products to 0.2, i am using your version 1.4.1 because i am running EPiServer 8.x.

**Comment by frederikvig** [comment]
Not sure how it works for older Commerce versions and the edit UI, but it's just saved as string so you should be able to set it through code at least.
