### ISSUE TITLE
http / http bug in the GetSiteHosts method

### ISSUE THREAD

**Issue by oyvindwh** [Geta/SEO.Sitemaps#30]
If the main site (in website url settings in admin) is http, but a subsite has https (or the other way around) the schema for the sitemap is set wrong. In the GetSiteHosts method the website url schema settings is used and not the host name schema.
 
https://github.com/Geta/SEO.Sitemaps/blob/master/Geta.SEO.Sitemaps/Modules/Geta.SEO.Sitemaps/AdminManageSitemap.aspx.cs (line 351)

var schema = "http";
if (host.UseSecureConnection != null && host.UseSecureConnection == true)
{
schema = "https";
}

**Comment by frederikvig** [comment]
Thanks Øyvind, will be part of next release.

**Comment by frederikvig** [comment]
Fixed in version 1.5.6
