### ISSUE TITLE
Is 1.5 backwards compatible with EpiServer 7

### ISSUE THREAD

**Issue by fatso83** [Geta/SEO.Sitemaps#34]
We are currently using version 1.1.2.0 in our EpiServer 7 site. I see that this version used ScheduledJobBase, which is not included in Epi 7. Would this mean that we cannot upgrade to this version until we run Epi 9 or later?

**Comment by frederikvig** [comment]
If you're still running Episerver 7 I would fork this repo and degrade the dependencies to Episerver 7. There should be very few changes required to make it work.
