### ISSUE TITLE
Extend/Add additional site map generators

### ISSUE THREAD

**Issue by fatso83** [Geta/SEO.Sitemaps#35]
We need to create a scheduled job that generates a html sitemap. Basically what this plugin does, but with different output format. After looking into this code, I found that I would be duplicating a lot of the existing effort put into this plugin. So I was wondering if there was a way of extending this solution with my own SiteMap?

I would need to 
- add a custom route
- add a custom "OutputProcessor"

Is there a way of doing this without modifying the plugin code?

**Comment by marisks** [comment]
Duplicate #36
