### ISSUE TITLE
Does not respect Accept-Encoding header

### ISSUE THREAD

**Issue by fatso83** [Geta/SEO.Sitemaps#37]
The module always output gzip encoding, no matter what encoding the client has specified as acceptable. This is a violation of the [HTTP W3 spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.3), which states:

<blockquote>If an Accept-Encoding field is present in a request, and if the server cannot send a response which is acceptable according to the Accept-Encoding header, then the server SHOULD send an error response with the 406 (Not Acceptable) status code.
</blockquote>
<blockquote>
If no Accept-Encoding field is present in a request, the server MAY assume that the client will accept any content coding. In this case, if "identity" is one of the available content-codings, then the server SHOULD use the "identity" content-coding, unless it has additional information that a different content-coding is meaningful to the client.
</blockquote>

I could supply a PR to check for the header before adding the `Response.Filter`?

Failing test:
```
curl -H "Accept-Encoding: foo" -I https://meny.no/sitemap.xml
```

**Comment by frederikvig** [comment]
That would be great, thanks.
