### ISSUE TITLE
EPiServer7 compatibility

### ISSUE THREAD

**Issue by ggroot** [Geta/SEO.Sitemaps#4]
How can i add SEOSitemaps as a property in my model?

If i use this, then I only see an empty textbox in the admin ui.

```
    [Searchable(false)]
    [BackingType(typeof(PropertySEOSitemaps))]
    [Display(
        Name = "Google Sitemap",
        GroupName = GroupNames.MetaData,
        Order = 50)]
    public virtual string SEOSitemaps { get; set; }
```

**Comment by tsebring** [comment]
Does this still work in EPiServer 7.5? The property renders with the regular string control for me.

**Comment by ggroot** [comment]
This worked for me:

        [UIHint(UIHint.Legacy, PresentationLayer.Edit)]
        [BackingType(typeof(PropertySEOSitemaps))]
        [Display(
            Name = "Google Sitemap",
            GroupName = GroupNames.MetaData,
            Order = 50)]
        public virtual string SEOSitemaps { get; set; }
