### ISSUE TITLE
Question : Error creating sitemap for "sitemap.xml"

### ISSUE THREAD

**Issue by shreyasingh25** [Geta/SEO.Sitemaps#40]
Hello,

I have recently upgraded my EPiServer framework to 9.12.2, and installed the sitemap via nuget
I have set the root as  -1, However when I run the task, I keep on getting this message ,
" Job successfully executed.
Generated sitemaps: 
Error creating sitemap for "sitemap.xml" " . How do i debug this error? 
I have tried checking write permission to the wwwroot folder, which looks fine to me. What else could be going wrong here?

**Comment by frederikvig** [comment]
Anything in the logs if you turn on debug logging?

**Comment by shreyasingh25** [comment]
Hello,

This is from the error log,

"
ERROR Geta.SEO.Sitemaps.XML.SitemapXmlGenerator: Error on generating xml
sitemap
System.ArgumentNullException: Parameter has no value set
Parameter name: contentLink
   at
EPiServer.Core.DefaultContentRepository.GetLanguageBranches[T](ContentReference
contentLink)
   at
Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.GetLanguageBranches(ContentReference
contentLink)
   at
Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.GenerateXmlElements(IEnumerable`1
pages)
   at
Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.CreateSitemapXmlContents(Int32&
entryCount)
   at Geta.SEO.Sitemaps.XML.SitemapXmlGenerator.Generate(SitemapData
sitemapData, Boolean persistData, Int32& entryCount)
"

Thanks,
Shreya

**Comment by IQndk** [comment]
I got this exact same problem, did you find a solution?

**Comment by Im5tu** [comment]
I narrowed mine down to having the root page id set as default (0). As soon as I changed this to the actual home page my error went away.
