### ISSUE TITLE
How do I enable the Language dropdown?

### ISSUE THREAD

**Issue by MiaHolmberg** [Geta/SEO.Sitemaps#43]
Hi,
I would like to use the language and language fallback settings that you have in you plugin, but I cant find where to enable this? 

The only way I find right now is to set it to true in AdminManageSitemap.aspx, but It would be nice to have a setting for it in admin mode so that it wont get overridden when updating the nuget package. 

Thanks!
/Mia

**Comment by MiaHolmberg** [comment]
Hello again,

Got it to work by enabling it through the web.config. Would be nice if you included that in the documentation :)

<configuration>
<configSections>
<section name="SitemapSettings" type="Geta.SEO.Sitemaps.Configuration.SitemapConfigurationSection, Geta.SEO.Sitemaps"/>
</configSections>

  <Geta.SEO.Sitemaps>
    <settings enableLanguageDropDownInAdmin="true" />
  </Geta.SEO.Sitemaps>
</configuration>

**Comment by frederikvig** [comment]
Thanks, added now :).

**Comment by MiaHolmberg** [comment]
Great thanks!
But I found a mistake in the code I sent you. The section name must be "Geta.SEO.Sitemaps" :)

```
<configuration>
<configSections>
<section name="Geta.SEO.Sitemaps" type="Geta.SEO.Sitemaps.Configuration.SitemapConfigurationSection, Geta.SEO.Sitemaps"/>
</configSections>

  <Geta.SEO.Sitemaps>
    <settings enableLanguageDropDownInAdmin="true" />
  </Geta.SEO.Sitemaps>
</configuration>
```

**Comment by frederikvig** [comment]
Ah missed that as well, updated now :).
