### ISSUE TITLE
Priority is always 1.0 on all pages - v1.4.2

### ISSUE THREAD

**Issue by francesnicola** [Geta/SEO.Sitemaps#45]
Hi,

I have version 1.4.2 and I couldn't upgrade to 1.5.1 because it's dependent on EPiServer 9 which my project is not ready to take on yet. The sitemaps are generated fine but all pages have priority of 1. When I looked at the latest source code that calculates the priority, I could see in the class SitemapXmlGenerator.cs the following code:

`int depth = new Uri(url).Segments.Length - 1;`
`return Math.Max(1.0 - (depth / 10.0), 0.5).ToString(CultureInfo.InvariantCulture);`

The logic looks correct as it considers the depth, but in 1.4.2 it seems to be not. How can I grab the source code of 1.4.2 so I can change the code manually and use this in my solution?

Thanks,
Nicola

**Comment by frederikvig** [comment]
You would need to check the commit history back to August 25th 2015. I would recommend using the latest code instead and just downgrading the Episerver dependency to version 8.0.0 instead.

Hope this helps.

Frederik

**Comment by francesnicola** [comment]
Hi Frederik,

Thanks for the response. Just how do I install latest without upgrading the dependency via Nuget? I tried installing latest and selected the option "Ignore dependencies" so it wouldn't update EPiServer, but after installing, it wouldn't build since it's dependent on EPiServer 10.

Thanks
