### ISSUE TITLE
Error while creating sitemap

### ISSUE THREAD

**Issue by mentius** [Geta/SEO.Sitemaps#46]
Hi,

I've installed version 1.5.7 for Episerver 9 and when I try to create a sitemap for standard and products I get the following error:
`Activation error occurred while trying to get instance of type ICommerceAndStandardSitemapXmlGenerator, key "" [No default Instance is registered and cannot be automatically determined for type 'Geta.SEO.Sitemaps.XML.ICommerceAndStandardSitemapXmlGenerator' There is no configuration specified for Geta.SEO.Sitemaps.XML.ICommerceAndStandardSitemapXmlGenerator 1.) Container.GetInstance(Geta.SEO.Sitemaps.XML.ICommerceAndStandardSitemapXmlGenerator) ]`
No error when creating a standard sitemap though.

Hope anyone can help!

Thanks,

Mark

**Comment by frederikvig** [comment]
It looks like you`re missing the Commerce sitemaps package.

**Comment by mentius** [comment]
Hi Frederkik,

Seems logical :) will try this. Thanks for the quick reply.

/Mark
