### ISSUE TITLE
Route customisation multi language is used

### ISSUE THREAD

**Issue by radu-negrila** [Geta/SEO.Sitemaps#47]
Hi,

Is it possible to customize the language segment that is generated by the tool when multi-language is used?

In my case the following url returns a 404, I guess it get's picked up by EPiServer routing
/en-us/Sitemap.xml
The sitemap gets generated since I can see it with the View link.

Thanks in advance, great tool BTW.

Radu

**Comment by frederikvig** [comment]
Hi
Just to confirm: /sitemap.xml works, but /en-us/sitemap.xml doesn't? Which URL is used by the view link?

Thanks

Frederik

**Comment by radu-negrila** [comment]
Hi Frederik,

Yes that is the case. 
Both /sitemap.xml and /en-us/sitemap.xml work if I click the View link. It opens the sitemap through javascript on the same URL as the plugin path -> cannot be used externally.

If I put the defined urls in the browsers, only /sitemap.xml works.
My guess is EPiServer tries to handle the request and than returns a 404.

Thanks

**Comment by radu-negrila** [comment]
After further investigation my problem was caused by a custom route.

Sorry for the false issue and thanks again for the great plugin.

Regards,
Radu

**Comment by frederikvig** [comment]
No problem, closing this issue now.
