### ISSUE TITLE
Sitemap.xml isn't generated at the root folder 

### ISSUE THREAD

**Issue by shreyasingh25** [Geta/SEO.Sitemaps#48]
Hi,

I am having issues getting the sitemap.xml file created in my root.
When I run the job everything completes successfully and if i click the view option from admin I do see the pages. 
When I look for the sitemap file it doesn't exist. I searched the drive without any luck. I have also checked that i have write permission to the root folder.

**Comment by patkleef** [comment]
Hi @shreyasingh25,

Sorry for the late response. The sitemap is stored in the database via DDS (dynamic data store). Custom routes have been added to make sure the sitemap is displayed when the URL, e.g. /sitemap.xml is called.
