### ISSUE TITLE
Expired Content is still added to the sitemaps

### ISSUE THREAD

**Issue by benhamino** [Geta/SEO.Sitemaps#49]
it looks like sitemaps are still being generated with content that is expired, this leads to broken pages being set for indexing

**Comment by MiaHolmberg** [comment]
Hi! Any updates on this issue?

**Comment by patkleef** [comment]
Hi @benhamino and @MiaHolmberg,

I tried to reproduce this on a clean Alloy demo site, but it seems to work. Which version of EPiServer are you using?

![image](https://cloud.githubusercontent.com/assets/2243586/25935875/751faf2c-3625-11e7-9912-b02dc5566582.png)

![image](https://cloud.githubusercontent.com/assets/2243586/25935899/8e7c6a6e-3625-11e7-830c-19f74162e33f.png)

**Comment by frederikvig** [comment]
Closing this because of lack of response. Feel free to reopen if needed.
