### ISSUE TITLE
Is possible to add additional links to the generated sitemap

### ISSUE THREAD

**Issue by juanjardim** [Geta/SEO.Sitemaps#52]
We have some links under the our website that are not yet migrated to epiServer. We would like to include those links in the generated sitemap.

Is it possible?

Thank you

**Comment by frederikvig** [comment]
You can include them if you create your own generator. See https://github.com/Geta/SEO.Sitemaps/tree/master/src/Geta.SEO.Sitemaps/XML for more details.
