### ISSUE TITLE
Scheduled job runs successfully, but 0 entries

### ISSUE THREAD

**Issue by siljesle** [Geta/SEO.Sitemaps#53]
We have the sitemap on our site, and the job runs and creates a sitemap with entries on my environment. On all our test and production environments the job runs successfully, but create no entries.

**Comment by frederikvig** [comment]
Could the configuration be wrong in these environments? I would check under sitemap settings and root page ID.

**Comment by siljesle** [comment]
No I don`t think so, we tried different id`s also. Both the id for the startpage and other id`s for different nodes in the pagetree. The job runs, but it`s done after less than a second so it seems it never traverse anything, just starts and stops and say it ran successfully.

**Comment by frederikvig** [comment]
Could you also see if you have the wildcard mapping setup under manage sites?

![image](https://user-images.githubusercontent.com/1058446/28522078-9b4e8e6c-7044-11e7-8f44-f08baa0c7d0c.png)

If not try adding it and running the job again.

**Comment by siljesle** [comment]
We don`t use wildcard mapping, but I tried adding it but it still don`t generate at sitemap with entries.

**Comment by mbrage83** [comment]
I have the same issue as well. I've also tried setting different id's not no entries in the Sitemap is generated. No errors in the log-files.

**Comment by siljesle** [comment]
Someone said  you need at usergroup "Everyone" with reading rights on the site for it to work, i haven`t tested it

**Comment by mbrage83** [comment]
I tried that as well but it makes no difference.

**Comment by vibran** [comment]
Did you find a solution to this problem? We're experiencing the the same problems.

**Comment by mbrage83** [comment]
@vibran Sorry for late reply.  A similar problem occured for me today. I solved it by removing the sitemap from the settings and creating a new one with -1 as root. And then running the scheduled job again. This is a weird issue...

**Comment by vibran** [comment]
Usergroup "Everyone" with reading rights on the site worked for us.

**Comment by DigIntSys** [comment]
Hi @siljesle. Did you find a solution for this issue or do you need more assistance?

**Comment by siljesle** [comment]
@DigIntSys  No, when we added the "Everyone" group it worked.

**Comment by DigIntSys** [comment]
Thank you for you reply @siljesle. Good to hear it's working.
