### ISSUE TITLE
Pages from custom content provider not listed in site map

### ISSUE THREAD

**Issue by johnligt** [Geta/SEO.Sitemaps#55]
We are using a custom content provider which programmatically adds pages to the EpiServer content tree on startup, based on data from an external database.  EpiServer Find indexes these pages, but somehow SEO.Sitemaps does not add these pages to the generated sitemap. What can I do to have these pages added to the sitemap?

**Comment by frederikvig** [comment]
You can add your custom XML generator that will also include anything from custom content provider. You can see an example here: https://github.com/Geta/SEO.Sitemaps/blob/master/src/Geta.SEO.Sitemaps/XML/SitemapXmlGenerator.cs

**Comment by DigIntSys** [comment]
Hi @johnligt . Have you managed to add the pages to the generated sitemap? If so i will close this issue.
Regards

**Comment by johnligt** [comment]
Hi Rui,

In the pages from the custom content provider the property "ExistingLanguages" was not set. After I set this property the problem was solved.

Regards,
John
