### ISSUE TITLE
Wrong URL rendered in output

### ISSUE THREAD

**Issue by mentius** [Geta/SEO.Sitemaps#56]
Hi,

When we render the sitemap for our client the <loc /> element is rendered as follows:
`https://shop.beterbed.nl/beterbed/boxsprings/box-cordoba-vlak-131d1a56/`
The URL should be:
`https://shop.beterbed.nl/boxsprings/vlakke-boxsprings/box-cordoba-vlak/?variationCode=474153`
This is not the correct URL. How can we change this? 

Thanks!

/Mark

**Comment by frederikvig** [comment]
Hi Mark
With a custom generator, see: https://github.com/Geta/SEO.Sitemaps/blob/master/src/Geta.SEO.Sitemaps/XML/StandardSitemapXmlGenerator.cs for example.

**Comment by mentius** [comment]
Hi, 

Thanks for the quick response. Will try this.

/Mark
