### ISSUE TITLE
404 Error while opening the Tools->Search Engine Sitemap Settings

### ISSUE THREAD

**Issue by BorisSokolov** [Geta/SEO.Sitemaps#57]
We are using 10th version of EPiServer Commerce.

When the application is deployed on the Test server - it is not possible to open the Tools->Search Engine Sitemap Settings. The url is like Modules/Geta.SEO.Sitemaps/AdminManageSitemap.aspx

It simply throws 404 without saying anything in the log.

Do you have some workarounds or ideas for such cases? 

Locally the same code works just fine.

**Comment by frederikvig** [comment]
Did the .aspx file get deployed to the server?

**Comment by BorisSokolov** [comment]
Yes

**Comment by BorisSokolov** [comment]
And redeployment with clean-up doesn't help

**Comment by BorisSokolov** [comment]
Looked like our build/deploy process issue
