### ISSUE TITLE
Tool crahses on Add New Sitemap

### ISSUE THREAD

**Issue by BorisSokolov** [Geta/SEO.Sitemaps#58]
After updating to the 1.6.4 Epi tool started to crash on pressing Add New Sitemap button.

Looks like the AntiForgery token causes this issue

**Comment by frederikvig** [comment]
Hi Boris, I just tested version 1.6.4 on a new site and add new sitemap worked without problems. Could reinstalling the package? Was there anything particular you did for adding the new sitemap when it crashed?

**Comment by BorisSokolov** [comment]
Hi Frederik! I have simply uninstalled 1.6.3 and installed 1.6.4 version instead. I was just pressing the button that's all. It looks like cookie was not saved. Adding the response headers so maybe it could help to analyse:
The first request headers that loads the page:
 
GET /Modules/Geta.SEO.Sitemaps/AdminManageSitemap.aspx HTTP/1.1
Host: tst-www.beerwulf.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://tst-www.beerwulf.com/EPiServer/CMS/Admin/Menu.aspx
Cookie: __cfduid=df2c08efa607cb37673bf6ab75b2ca24b1493037795; _ga=GA1.2.442805312.1493037798; mf_user=7a15637e008f54cd27f67ffcfe37b948|; _ga=GA1.3.442805312.1493037798; BrowsingHistory=qYarHZ6QGxKKdcVtHKTxQM6mndFfhkS7EH8zH3CVxioY4wyZ50yrhQptL2FFxVLZlYjmGnScz1iZ5RcX+lkbdyDZnv8psxhOeNOjq9Bh6VRFx+kaMhnrOxzlIEjeqbT6eL5OM7y0G5nKEqAh5gS2wK20RtJAAf078EV9AdwplnQXkCgqOVr8ux31BD88scgGUinDp/yGlkFwBAzAD/p8UFT48BUwDa30YiqvjJQdiDgZ8k4gdJgEnzJT1WERyuje5OrP1nqG2XTIrcTB4TxAly4rG+kbuJLPIl6f56OsqTJKLzQ76K8ulZrh50mpmvyQBs7OFA==; _cs_id=977a9511-a641-a1b6-dab3-3b8d4f083598.1496048646.81.1503586106.1503585123.1.1532124667967; uxt_2701=1; uxt_2705=0; _cs_v=0; _cs_r=0; ASP.NET_SessionId=0us4nkbmd4abqojyzirrwidi; cookiesAccepted=1; ageCheck=true; ARRAffinity=247d259187d416b4caf5a31ae182652c08413d54025c6ddfe8b19c02b1123392; uxt_2761=1; _gid=GA1.3.602904895.1503488759; .EPiServerLogin=540876CD4C84C891CFA47AC5EA471B07086F57DD5D606E076C9F2A166D10FBFB1FC6E803412E1AD2BA59BBED481B02C8AC6452E6C5E35A44D04D7F1375B43E598CDEA6769F0479521360E9A28FE9055FCF8715F0; _gid=GA1.2.1604187128.1503563042; .ASPXROLES=Fzc-FOkTPUnhECVkuSzim1uSLPr7MJznsJpGG0f2P6Knj_GC2v7yfYI3y0-yXNGtWC4mVsSrtQ0s2XY7RL2rqVpX7fzexUuV3rYEepT3VU40H8f9cgZvWI5o26K_GGBgtqJ8jPcFr6UW0Kr3YMAr73xi0y6fiJZZ-fuXTHXbMGCvhPv9qCPvS5sXhc7pfdXqSPUVAfC9zRO1bbEh-kmUuhZmXHNuPLJljR_6e_CWvfgqcBsTK598ZuG3z1gMQNz81YJOAdfx4ZS5uQttJBZ7hGBDEXtuuyFF_lfg-VA_LSIB0wKh2L6X5xT4cudfXP9n6Xs3e-Nek3YGsrr7GFAnHCgwHuoh-a86-KcFmF5Nts9KYPNbZ0oWPgt0IA1xBwuhVLhJ4Pt4jCKv19EwnCVIeoYduKj6I0Ecn5CcNR9LL7WeLeeu2UuWnf0HOg8YCh-XvnWMWSiZ7opLxR2QlFqmUHHTfG5PWWUDVbOqF36Heb7cPPAILSbh-6gmaE5RnuhtyAv10w2; __epiXSRF=wOlCPAzENW5132XLbpxwql5f/Jr7QITfuvgWJ2xCz2A=; _cs_s=3
Connection: keep-alive
Upgrade-Insecure-Requests: 1
 
Response headers:
HTTP/2.0 200 OK
Date: Thu, 24 Aug 2017 14:51:47 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 2639
Cache-Control: private
Content-Encoding: gzip
Expires: Wed, 23 Aug 2017 14:51:46 GMT
Vary: Accept-Encoding
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
arr-disable-session-affinity: true
Server: cloudflare-nginx
cf-ray: 393721b479127337-AMS
X-Firefox-Spdy: h2
 
The second request on pressing the button that gets 500 error as a result:
POST /Modules/Geta.SEO.Sitemaps/AdminManageSitemap.aspx HTTP/1.1
Host: tst-www.beerwulf.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://tst-www.beerwulf.com/Modules/Geta.SEO.Sitemaps/AdminManageSitemap.aspx
Content-Type: application/x-www-form-urlencoded
Content-Length: 531
Cookie: __cfduid=df2c08efa607cb37673bf6ab75b2ca24b1493037795; _ga=GA1.2.442805312.1493037798; mf_user=7a15637e008f54cd27f67ffcfe37b948|; _ga=GA1.3.442805312.1493037798; BrowsingHistory=qYarHZ6QGxKKdcVtHKTxQM6mndFfhkS7EH8zH3CVxioY4wyZ50yrhQptL2FFxVLZlYjmGnScz1iZ5RcX+lkbdyDZnv8psxhOeNOjq9Bh6VRFx+kaMhnrOxzlIEjeqbT6eL5OM7y0G5nKEqAh5gS2wK20RtJAAf078EV9AdwplnQXkCgqOVr8ux31BD88scgGUinDp/yGlkFwBAzAD/p8UFT48BUwDa30YiqvjJQdiDgZ8k4gdJgEnzJT1WERyuje5OrP1nqG2XTIrcTB4TxAly4rG+kbuJLPIl6f56OsqTJKLzQ76K8ulZrh50mpmvyQBs7OFA==; _cs_id=977a9511-a641-a1b6-dab3-3b8d4f083598.1496048646.81.1503586106.1503585123.1.1532124667967; uxt_2701=1; uxt_2705=0; _cs_v=0; _cs_r=0; ASP.NET_SessionId=0us4nkbmd4abqojyzirrwidi; cookiesAccepted=1; ageCheck=true; ARRAffinity=247d259187d416b4caf5a31ae182652c08413d54025c6ddfe8b19c02b1123392; uxt_2761=1; _gid=GA1.3.602904895.1503488759; .EPiServerLogin=540876CD4C84C891CFA47AC5EA471B07086F57DD5D606E076C9F2A166D10FBFB1FC6E803412E1AD2BA59BBED481B02C8AC6452E6C5E35A44D04D7F1375B43E598CDEA6769F0479521360E9A28FE9055FCF8715F0; _gid=GA1.2.1604187128.1503563042; .ASPXROLES=Fzc-FOkTPUnhECVkuSzim1uSLPr7MJznsJpGG0f2P6Knj_GC2v7yfYI3y0-yXNGtWC4mVsSrtQ0s2XY7RL2rqVpX7fzexUuV3rYEepT3VU40H8f9cgZvWI5o26K_GGBgtqJ8jPcFr6UW0Kr3YMAr73xi0y6fiJZZ-fuXTHXbMGCvhPv9qCPvS5sXhc7pfdXqSPUVAfC9zRO1bbEh-kmUuhZmXHNuPLJljR_6e_CWvfgqcBsTK598ZuG3z1gMQNz81YJOAdfx4ZS5uQttJBZ7hGBDEXtuuyFF_lfg-VA_LSIB0wKh2L6X5xT4cudfXP9n6Xs3e-Nek3YGsrr7GFAnHCgwHuoh-a86-KcFmF5Nts9KYPNbZ0oWPgt0IA1xBwuhVLhJ4Pt4jCKv19EwnCVIeoYduKj6I0Ecn5CcNR9LL7WeLeeu2UuWnf0HOg8YCh-XvnWMWSiZ7opLxR2QlFqmUHHTfG5PWWUDVbOqF36Heb7cPPAILSbh-6gmaE5RnuhtyAv10w2; __epiXSRF=wOlCPAzENW5132XLbpxwql5f/Jr7QITfuvgWJ2xCz2A=; _cs_s=3
Connection: keep-alive
Upgrade-Insecure-Requests: 1
 
Response headers:
HTTP/2.0 500 Internal Server Error
Date: Thu, 24 Aug 2017 14:55:31 GMT
Content-Type: text/html
Cache-Control: private
Expires: Wed, 23 Aug 2017 14:55:30 GMT
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=63072000; includeSubdomains; preload
arr-disable-session-affinity: true
Server: cloudflare-nginx
cf-ray: 3937272c88937337-AMS
X-Firefox-Spdy: h2

**Comment by BorisSokolov** [comment]
Just tested locally on Alloy website and it works fine there...

**Comment by neveup** [comment]
Hi Boris, Did ever resolve this issue? I think i am getting the same issue with 1.6.7.

**Comment by BorisSokolov** [comment]
Hi. 

We haven't resolved the issue. Just turned the AntiForgery off as a workaround. I don't feel that it is critical to have it

**Comment by larswp** [comment]
How did you turn it of? because i have the same problem

**Comment by BorisSokolov** [comment]
https://github.com/Geta/SEO.Sitemaps/blob/master/src/Geta.SEO.Sitemaps/Modules/Geta.SEO.Sitemaps/AdminManageSitemap.aspx

Try to remove line12:
`<%= System.Web.Helpers.AntiForgery.GetHtml() %>`

**Comment by larswp** [comment]
that does not turn it of. It just removes the client side part then the server will newer be able to validate the antiforgery token, and it should fail every time.

**Comment by larswp** [comment]
i cleared my cookies and now it works *facepalm*

**Comment by DigIntSys** [comment]
Hi @BorisSokolov and @larswp . Did you manage to use the tool with the anti forgery token?

**Comment by larswp** [comment]
I did, yes

**Comment by BorisSokolov** [comment]
Hi @DigIntSys ,

I was able to use it with anti forgery tokens on many other sites and it was OK. On the one that had initial issue - I cannot say that as the customer had some exotic requirements and they were implementing their custom sitemap generator

**Comment by DigIntSys** [comment]
That's good to hear @BorisSokolov. Not sure if we can provide support for a custom generator. Your customer might need to find a solution if the problem persists, but I would recommend sticking with the  anti forgery token. I will close this issue for now. If the problem persists for your customer and there is something that we can do about it, let us know.
Regards.
Rui Vaz
