### ISSUE TITLE
[Question] Is it possible to generate sitemap.xml per language?

### ISSUE THREAD

**Issue by BorisSokolov** [Geta/SEO.Sitemaps#59]
We have a multicultural site (on the same domain) and interested if it is possible to generate separate sitemap files per culture.

Thanks in advance

**Comment by DigIntSys** [comment]
Hi again @BorisSokolov . Have you managed to solve this issue?
One of way of achieving what you want is to create separate settings per site culture and for each setting, you avoid the language path that you don't want.
for example:
![capture](https://user-images.githubusercontent.com/30575582/39750747-5710f0aa-52b6-11e8-9673-68a67b5c67bf.PNG)

Let me know if this fits your needs. 
Regards, Rui

**Comment by BorisSokolov** [comment]
Hi @DigIntSys ,

Yes. We were using this solution
