### ISSUE TITLE
Setting default value on specific page types

### ISSUE THREAD

**Issue by Hyzac** [Geta/SEO.Sitemaps#64]
Is there a way to set the SEOSitemaps property to be disabled on specific pagetypes? I have tried setting the serialized string value of the property in the get method but it doesn't use that value it seems.

This is what I have tried 
```
public virtual string SEOSitemaps {
            get
            {
                var sitemapSetting = this.GetPropertyValue(x => x.SEOSitemaps);
                if (this.PageTypeName == "InformationPage")
                {
                    return string.IsNullOrWhiteSpace(sitemapSetting) ? "<SEOSitemaps><enabled>False</enabled><changefreq>weekly</changefreq><priority>0.5</priority></SEOSitemaps>" : sitemapSetting;
                }
                return sitemapSetting;
            }
            set
            {
                this.SetPropertyValue(b => b.SEOSitemaps, value);
            }
        }
```

**Comment by andemt** [comment]
Use override SetDefaultValues:
`public override void SetDefaultValues(ContentType contentType) 
{
            base.SetDefaultValues(contentType);
            this.SEOSitemaps = "<SEOSitemaps><enabled>False</enabled><changefreq>never</changefreq><priority>0.0</priority></SEOSitemaps>";
        }`

It would be nice if Geta would have some public methods, so we could do this:
`public override void SetDefaultValues(ContentType contentType)
{
            base.SetDefaultValues(contentType);
            var sitemap = new PropertySEOSitemaps
            {
                Enabled = false
            };
            this.SEOSitemaps = sitemap.Serialize();
}`

**Comment by marisks** [comment]
I see that PropertySEOSitemaps has Serialize as a public method: https://github.com/Geta/SEO.Sitemaps/blob/bddff176af2a9503e625f1d44bd78b73ac3f6217/src/Geta.SEO.Sitemaps/SpecializedProperties/PropertySEOSitemaps.cs#L100

Doesn't it work?

**Comment by ipoley-r7** [comment]
I'm confused how this is to be used? The `Serialize()` method sets the protected `String` property, which can't be read and used to set the new property's value.

**Comment by tomahg** [comment]
@marisks Serialize() is public but it's void. It writes to a property that is not public.

Is there no way to exclude specific page types?

**Comment by MarkMcDonald** [comment]
For reference this works:

```
        public override void SetDefaultValues(ContentType contentType)
        {
            base.SetDefaultValues(contentType);
            var sitemap = new PropertySEOSitemaps
            {
                Enabled = false
            };
            sitemap.Serialize();
            this.SEOSitemaps = sitemap.ToString();
        }
```

**Comment by patkleef** [comment]
Thanks @MarkMcDonald , I added it to the readme and made an example in the sample site

https://github.com/Geta/SEO.Sitemaps#set-default-value
