### ISSUE TITLE
Assembly does not have a strong name

### ISSUE THREAD

**Issue by AlexMedia** [Geta/SEO.Sitemaps#65]
On the EPI project that I'm currently working on, all assemblies are signed with a strong name during build. The Geta.SEO.Sitemaps.dll does not seem to have a strong name attached to it, so I can't use it.

Can you please sign your assemblies before publishing them?

**Comment by marisks** [comment]
We do not have plans for signing library assemblies as it is not required in most cases. Even not all of Episerver's dependent assemblies are signed.
But if you need it, you can use the source code of this library and create your own NuGet packages with signed assemblies. The library is under MIT license, so you are free to do it.
