### ISSUE TITLE
Issue with Geta.SEO.Sitemap.Commerce

### ISSUE THREAD

**Issue by aniruddhaghosh** [Geta/SEO.Sitemaps#67]
I am trying to use Geta.SEO.Sitemap.Commerce for creating a sitemap for commerce/catalog. For this I am running the scheduled job from the admin panel. It creates the sitemap for CMS and Commerce successfully. At the end of the job it creates the sitemap for CMS with some entries but creates 0 entries for commerce. Permissions should not be an issue here as I am logged in as an admin. And also tried to add a wildcard (*) as described in another issue here. Please help us setting up a commerce sitemap.
Thanks.

**Comment by DigIntSys** [comment]
Hi @aniruddhaghosh .
Do you still need help regarding this issue? This could be related to the permissions on the pages. Have you tried setting the root permissions to everyone and then restricting the pages that are not meant to be seen?

Regards,
Rui Vaz

**Comment by marisks** [comment]
Closing issue for now. If you experience this again, please open a new issue.
