### ISSUE TITLE
404 error on the generated XML

### ISSUE THREAD

**Issue by mkadiwar** [Geta/SEO.Sitemaps#68]
Hi,

I have install the Geta.Seo.Sitemap in my project, after installation we are getting some issue when generate sitemap. It seems all xml is created when running the sitemap job but when you click on url it give 404 error.

Following is the structure of our site

XYZ_PublicWeb -- In manage Website, and under that we have all the language domain

www.xyz.com 

www.xyz.ae

www.xyz.zh

www.xyz.fr

etc

In Serach engine sitemap Settings tools, we define domain as

www.xyz.com/en/sitemap.xml

www.xyz.ae/ae/sitemap.xml

www.xyz.zh/zh/sitemap.xml

www.xyz.fr/fr/sitemap.xml

language is add in url becasue we selected language in each domain while creating sitemap.

Thanks in Advance

**Comment by DigIntSys** [comment]
Hi @mkadiwar . Do you still need help on this issue?
Regards,
Rui Vaz

**Comment by mkadiwar** [comment]
No, Thank you ☺

Br,
Malik Kadiwar
Consultant | AppsTwo CSD

Capgemini India | Mindspace, Airoli
Tel.: +91 2 26 68 60 500 (EXT: 2219406) – Mob.: + 91 70453 70317
www.capgemini.com<http://www.capgemini.com/>
[https://visualidentity.capgemini.com/capgemini.png]
____________________________________________________________________
Connect with Capgemini:
[cid:image010.png@01D35EC5.D54D2F50]<https://www.capgemini.com/insights-and-resources/blogs>[cid:image011.png@01D35EC5.D54D2F50]<https://www.twitter.com/capgemini> [cid:image012.png@01D35EC5.D54D2F50] <https://www.facebook.com/capgemini>  [cid:image013.png@01D35EC5.D54D2F50] <https://www.linkedin.com/company/capgemini>  [cid:image014.png@01D35EC5.D54D2F50] <https://www.youtube.com/capgeminimedia>  [cid:image015.png@01D35EC5.D54D2F50] <https://www.slideshare.net/capgemini>  [cid:image016.png@01D35EC5.D54D2F50] <https://plus.google.com/+CapgeminiGlobal>

Please consider the environment and do not print this email unless absolutely necessary.
Capgemini encourages environmental awareness.
