### ISSUE TITLE
Sitemaps doesn´t work on EPi-server hosting

### ISSUE THREAD

**Issue by BethLinden** [Geta/SEO.Sitemaps#69]
Hi,

the plugin works well on my local machine, when try to run it on integration or in production environment. I get the following response.

 Job successfully executed
generated sitemaps
error created sitemaps for...

The job runs for aprox 16-10s.

I work with a clone of the database on my local machine.

Can you help me or should I just uninstall your plugin?

regards,
Beth

**Comment by frederikvig** [comment]
Hi Beth, sounds like there might be some miss-configuration under manage sites, could you verify?

**Comment by BethLinden** [comment]
Hi,

In the attachment you can see the configurations. Can you see something wrong? (number 8 is the start node for home in integration)

Kind regards,
Beth

Beth Lindén
Systemutvecklare

Telefon:
Mobil: +46 (0)703-80 70 74
E-post beth.linden@netrelations.com

NetRelations

**Comment by BethLinden** [comment]
Hi agin,

<here is the logfile from Epi.


Beth Lindén
Systemutvecklare

Telefon:
Mobil: +46 (0)703-80 70 74
E-post beth.linden@netrelations.com

NetRelations

**Comment by bogdanstojanovic** [comment]
I have experienced the same. The issue on our side has got resolved once we removed restricted access from the page.

**Comment by DigIntSys** [comment]
Hi @BethLinden ,
Do you still need help with this issue?
Regards,
Rui Vaz

**Comment by marisks** [comment]
Closing issue for now. If you experience this again, please open a new issue.
