### ISSUE TITLE
The sitemap isn't validated

### ISSUE THREAD

**Issue by haspe85** [Geta/SEO.Sitemaps#73]
Hi!

I have a sitemap.xml from this addon and its created and I can visit it correctly. 

But when running a validate check with http://validator.w3.org/ it gives an error: 
Sorry! This document cannot be checked.

Missing "charset" attribute for "text/xml" document.

The HTTP Content-Type header (text/xml) sent by your web server (Microsoft-IIS/8.5) did not contain a "charset" parameter, but the Content-Type was one of the XML text/* sub-types.

The relevant specification (RFC 3023) specifies a strong default of "us-ascii" for such documents so we will use this value regardless of any encoding you may have indicated elsewhere.

If you would like to use a different encoding, you should arrange to have your server send this new encoding information.

Kind regards
/ Henric

**Comment by marisks** [comment]
This is fixed in 2.0.7. New library version pushed to the nuget.episerver.com but have to wait for it to be available.
