### ISSUE TITLE
404 opening Tools/Search Engine Sitemap Settings

### ISSUE THREAD

**Issue by be-prokom** [Geta/SEO.Sitemaps#82]
I get "The webpage at ..Modules/Geta.SEO.Sitemaps/AdminManageSitemap.aspx might be temporarily down or it may have moved permanently to a new web address." when opening Tools->Search Engine Sitemap Settings. I have Episerver.CMS verision 10.10.3.0. and I have tried version 1.6.7, 1.6.6 and 1.6.3 of Sitemaps.

Version 1.6.3 of Sitemap is working on another page I have with Episerver.CMS 10.9.10.0.

The file Modules/Geta.SEO.Sitemaps/AdminManageSitemap.aspx exists.

**Comment by patkleef** [comment]
In the past, there were some problems with routing. Recently we moved to Episerver's recommended zipped module which should solve all problems.

**Comment by MavApps** [comment]
Hello,
We recently started experiencing this issue after an upgrade to 11.14. 
The sitemap admin works fine in our local development environment (Visual Studio 2019, IIS Express) but gives a 404 in our integration and production environments of the DXC.

.net = 4.6.2
EPiServer.CMS = 11.14.0
Geta.SEO.Sitemaps = 3.1.2

**Comment by red7even** [comment]
i'm getting a 404 when trying to access the AdminManageSitemap.aspx on DXC, works fine on local VS 2019 environments, this does seem related to a recent upgrade to EPI 11.14.

**Comment by red7even** [comment]
in case anyone else gets this & can't fix it i managed to locate the view outside of the cms by going to:

/modules/geta.seo.sitemaps/adminmanagesitemap.aspx

Hope it helps.

**Comment by camistein** [comment]
> in case anyone else gets this & can't fix it i managed to locate the view outside of the cms by going to:
> 
> /modules/geta.seo.sitemaps/adminmanagesitemap.aspx
> 
> Hope it helps.

You just made my day, thank you! Got 404 on both azure and dxc but worked fine on local.
