### ISSUE TITLE
Sitemap Property not showing correct Enabled-value

### ISSUE THREAD

**Issue by tuube** [Geta/SEO.Sitemaps#97]
We have added the Sitemap-property to our pages. The "Enabled" value shows always as true after publish. The value is changed in the databse, it just doesn't show it on the edit page.

**Comment by patkleef** [comment]
@tuube do you use  the dynamic property or this one: 
https://github.com/Geta/SEO.Sitemaps#adding-sitemap-properties-to-all-content-pages

**Comment by tuube** [comment]
We are using the NOT-dynamic property that you linked.

**Comment by patkleef** [comment]
@tuube I'm not able to reproduce. Which version of the package have you installed? I tried with version 3.02.

**Comment by tuube** [comment]
We are using version 2.0.13. I'll try if the newer version works better.

**Comment by patkleef** [comment]
@tuube did you find the time to test with a newer version?

**Comment by tuube** [comment]
Yes, I finally did, and it works with version 3.1.0. Thanks for your help @patkleef !

**Comment by patkleef** [comment]
No problem, closing issue.
